# path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="msmall-agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
#DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(asdf aws colorize colored-man-pages docker extract git git-extras gnu-utils history-substring-search kubectl poetry terraform tmux vagrant virtualenv zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

unsetopt correct_all
setopt SHARE_HISTORY

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/

export ASDF_DATA_DIR="$HOME/.asdf"

export PATH=$ASDF_DATA_DIR/shims:$HOME/.local/bin:/usr/local/bin:$HOME/bin:$HOME/local/bin:/usr/sbin:/root/bin:/usr/local/bin:/bin:/usr/bin:/usr/games:/sbin

export EDITOR=emacs
export PAGER=less

export LC_CTYPE=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
export LANGUAGE=en_GB.UTF-8

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

eval "$(direnv hook zsh)"

export DOCKER_BUILDKIT=1
export BUILDKIT_PROGRESS=plain
export COMPOSE_DOCKER_CLI_BUILD=1
export COMPOSE_BAKE=true

export AZCOPY_AUTO_LOGIN_TYPE=AZCLI

source ~/.shell_aliases
source ~/.shell_secrets

setxkbmap gb
